language: node_js

node_js:
  - "10"

os:
  - linux
  # - osx
  # - windows

cache:
  npm: true
  directories:
    - node_modules

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run test:lint
      # Run the coverage test
      bash scripts/ci/test_coverage.sh
    else
      npm test
    fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -n "$TRAVIS_TAG" ]; then
      # Publish the package on npm
      bash scripts/ci/deploy.sh
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f6c7fbd99c6425464bbc
    on_cancel: change
    on_error: always
    on_failure: always
    on_start: change
    on_success: change
