language: node_js

node_js:
  - "10"

os:
  - linux
  # - osx
  # - windows

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      # Run the coverage test
      bash scripts/ci/test_coverage.sh

      if [ -n "$TRAVIS_TAG" ]; then
        # Publish the package on npm
        bash scripts/ci/deploy.sh
      fi
    fi
